# Generated by Django 3.2.6 on 2021-08-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Restaurant_image',
            field=models.ImageField(upload_to='restroimg'),
        ),
    ]
