# Generated by Django 3.2.6 on 2021-09-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_category_restaurant_restaurant_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restauranttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_category', models.CharField(choices=[('Fine Dining', 'Fine Dining'), ('Casual Dining', 'Casual Dining'), ('Contemporary Casual', 'Contemporary Casual'), ('Family Style', 'Family Style'), ('Fast Casual', 'Fast Casual'), ('Fast Food', 'Fast Food'), ('Cafe', 'Cafe'), ('Buffet', 'Buffet'), ('Food Trucks and Concession Stands', 'Food Trucks and Concession Stands'), ('Pop-Up Restaurant', 'Pop-Up Restaurant')], max_length=100)),
                ('Restaurant_image', models.ImageField(upload_to='restroimg')),
            ],
        ),
    ]
