# Generated by Django 3.2.6 on 2021-09-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210902_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Restro_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
