# Generated by Django 3.2.6 on 2021-09-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210926_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Restro_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='zipcode',
            field=models.CharField(max_length=6),
        ),
    ]
